[package]
name = "ripper"
version = "0.1.0"
authors = ["Kevin Cotugno <kevin@kevincotugno.com>"]

[[bin]]
name = "ripper"
path = "src/bin/client.rs"

[[bin]]
name = "ripper-server"
path = "src/bin/server.rs"

[lib]
name = "ripper"
path = "src/ripper/lib.rs"

[dependencies]
clap = "~2.32"
